queue_rules:
  - name: default
    merge_method: squash

  - name: rebase
    merge_method: rebase

pull_request_rules:
  - name: Auto Squash and Merge
    conditions:
      - base=master
      - check-success=ci
      - 'label=ready to squash and merge'
    actions:
      delete_head_branch: {}
      queue:
        name: default

  - name: Auto Rebase and Merge
    conditions:
      - base=master
      - check-success=ci
      - 'label=ready to rebase and merge'
    actions:
      delete_head_branch: {}
      queue:
        name: rebase
